language: node_js 
node_js: 
  - "node" 

sudo: required

install:
  - cd $PROJECT
  - npm install 
script:
  - npm run test

matrix:
  include:
    - env: PROJECT="API"
      services: mongodb
      cache: 
        directories: 
          - "API/node_modules" 
    - env: PROJECT="client"
      addons:
        chrome: stable
        cache:
          directories: 
            - "client/node_modules"
    - env: PROJECT="CKEditor"
      cache: 
        directories: 
          - "CKEditor/node_modules" 
