language: node_js

node_js:
  - "node"

services: mongodb

env:
  - project=api

cache:
  directories:
    - "API/node_modules"
    - "CKEditor/node_modules"
    - "client/node_modules"

before_install:
  - cd $TRAVIS_BUILD_DIR

install:
  - cd $project
  - npm install

before_script:
  - cd $TRAVIS_BUILD_DIR

script:
  - cd $project
  - npm run test
