language: node_js 
 
node_js: 
  - "node" 
 
services: mongodb 
 
env: 
  - DIR="API" 
  - DIR="client"
 
cache: 
  directories: 
    - "API/node_modules" 
    - "CKEditor/node_modules" 
    - "client/node_modules" 
 
install:
  - cd $DIR
  - npm install 
 
script:
  - npm run test 
