language: node_js 
node_js: 
  - "node" 
os: linux
dist: xenial

install:
  - cd $PROJECT
  - npm ci 
script:
  - npm run test

jobs:
  include:
    - env: PROJECT="API"
      services: mongodb
      cache: 
        directories: 
          - "API/node_modules" 
    - env: PROJECT="client"
      addons:
        chrome: stable
      cache:
        directories: 
          - "client/node_modules"
      before-install:
        - export NG_CLI_ANALYTICS=ci
    - env: PROJECT="CKEditor"
      cache: 
        directories: 
          - "CKEditor/node_modules" 
